Improve scripts.
Update mvn deploy syntax.
Add additional sanity checks.

diff --git a/publish-snapshot b/publish-snapshot
--- a/publish-snapshot
+++ b/publish-snapshot
@@ -21,7 +21,11 @@ echo "================================================================="
 user_continue
 
 # update pom to release version
-mvn clean && mvn package -Dmaven.javadoc.skip=true -B -V
+if ! mvn clean; then
+  echo "maven clean command failed, check your environment"
+  exit
+fi
+mvn package -Dmaven.javadoc.skip=true -B -V
 
 # Clone the maven repo
 pushd ${REPO_PATH}
@@ -29,7 +33,7 @@ git pull
 popd
 
 # Deploy the artifact to the maven repo
-mvn deploy -DskipTests -DaltDeploymentRepository=snapshot::default::file://${REPO_PATH}
+mvn deploy -DskipTests -DaltDeploymentRepository=snapshot::file://${REPO_PATH}
 
 # Push changes to the maven repo
 pushd ${REPO_PATH}
diff --git a/release b/release
--- a/release
+++ b/release
@@ -48,9 +48,18 @@ echo "================================================================="
 user_continue
 
 # update pom to release version
-mvn clean
+if ! mvn clean; then
+  echo "maven clean command failed, check your environment"
+  exit
+fi
 mvn versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false
 echo "Updated pom to release version ${RELEASE_VERSION}"
+
+POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+if [ "${POM_VERSION}" != "${RELEASE_VERSION}" ]; then
+  echo "POM version ${POM_VERSION} does not equal ${RELEASE_VERSION}"
+  exit
+fi
 user_continue
 
 # commit pom changes
